language: objective-c
osx_image: xcode9.3

script:
  - xcodebuild -project howlongtime.xcodeproj -scheme 'howlongtime' -sdk iphonesimulator build
  - xcodebuild test -project howlongtime.xcodeproj -scheme 'howlongtimeTests' -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.3'
  - xcodebuild test -project howlongtime.xcodeproj -scheme 'howlongtimeUITests' -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.3'